/**
 * Showcase ↔ system conformance (REQ-SHOWCASE-PAGE, ADR-0044).
 *
 * The standalone HTML showcase (`apps/web/public/showcase.html`, generated by
 * `scripts/build-showcase.mjs` from the committed `examples/showcase.json` manifest + the golden
 * `examples/showcase-<type>.svg` renders) is made UN-DRIFTABLE the same way the catalog is
 * (ADR-0027/0028): the manifest is checked against the SYSTEM, and the generated page is checked
 * against the manifest. So the showcase can never silently fall behind the language — adding the
 * 21st diagram type fails CI until the type has a showcase entry, and the page content can't drop a
 * diagram, its title, its render, or the honesty framing. It goes further than presence: the page
 * must embed each type's EXACT current golden SVG VERBATIM, and `index.test.ts` pins every golden to
 * the live renderer — so the chain page <- golden <- renderer is enforced end to end (improve a
 * renderer -> its golden regenerates -> the showcase shows the new render; a stale, rescaled,
 * re-rendered, or dropped diagram fails CI). Companion to `catalog.test.ts` and
 * `docs-conformance.test.ts`. Traceability: REQ-SHOWCASE-PAGE, REQ-EXAMPLE-LIBRARY.
 */
import { describe, expect, it } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { DiagramType } from '@psyuml/model';
import { FAMILIES, FAMILY_OF } from '@psyuml/profiles';
import { renderShowcase, esc } from '../scripts/build-showcase.mjs';

const TYPES = DiagramType.options;
const manifest = JSON.parse(readFileSync('examples/showcase.json', 'utf8'));

const titleOf = (t: string): string =>
  JSON.parse(readFileSync(`examples/showcase-${t}.psyuml`, 'utf8')).meta.title;
const svgOf = (t: string): string => readFileSync(`examples/showcase-${t}.svg`, 'utf8');

const familyTitleOf = (t: string): string => {
  const fam = FAMILIES.find((f) => f.id === FAMILY_OF[t as keyof typeof FAMILY_OF]);
  if (!fam) throw new Error(`no family for ${t}`);
  return fam.title;
};

describe('showcase ↔ system conformance (REQ-SHOWCASE-PAGE, ADR-0044)', () => {
  it('the manifest showcases EXACTLY the renderer types, one entry per type', () => {
    const listed = manifest.diagrams.map((d: { type: string }) => d.type);
    expect(new Set(listed), 'one showcase entry per DiagramType.options').toEqual(new Set(TYPES));
    expect(listed.length, 'no duplicate diagram entries').toBe(TYPES.length);
  });

  const diagramCases = (manifest.diagrams as Array<Record<string, string>>).map(
    (d): [string, Record<string, string>] => [d.type, d],
  );
  it.each(diagramCases)(
    '%s — entry is complete, honest-scoped, and its golden SVG + model exist',
    (type, d) => {
      expect(TYPES, `${type} is a real renderer type`).toContain(type);
      // the prose a reader actually leans on — each must carry real content
      for (const field of ['whatItShows', 'whenToUse', 'onPaper', 'evidenceNote'] as const) {
        expect(typeof d[field], `${type}.${field} is a string`).toBe('string');
        expect(d[field].trim().length, `${type}.${field} is substantive`).toBeGreaterThan(20);
      }
      for (const field of ['school', 'oneLiner'] as const) {
        expect(d[field]?.trim().length, `${type}.${field} present`).toBeGreaterThan(2);
      }
      expect(['C', 'L', 'B'], `${type}.audience is C|L|B`).toContain(d.audience);
      // family tracks the SYSTEM (FAMILY_OF) — a remap forces the manifest to follow
      expect(d.family, `${type} family must equal FAMILY_OF`).toBe(familyTitleOf(type));
      expect(existsSync(`examples/showcase-${type}.svg`), `golden svg for ${type}`).toBe(true);
      expect(existsSync(`examples/showcase-${type}.psyuml`), `model for ${type}`).toBe(true);
    },
  );

  it('the family chooser block mirrors the FAMILIES registry (id/title/question)', () => {
    const slim = (f: { id: string; title: string; question: string }) => ({
      id: f.id,
      title: f.title,
      question: f.question,
    });
    expect(manifest.families.map(slim)).toEqual(FAMILIES.map(slim));
  });

  it('the page-level guide carries the JTBD jobs, an on-paper guide, and the honesty triad', () => {
    expect(manifest.intro?.title?.length, 'intro title').toBeGreaterThan(0);
    expect(
      manifest.jobs.map((j: { id: string }) => j.id),
      'the four jobs-to-be-done are the page spine',
    ).toEqual(['read', 'paper', 'choose', 'honest']);
    expect(manifest.paperGuide.length, 'an on-paper drawing guide').toBeGreaterThan(0);
    expect(manifest.honesty.length, 'at least the honesty triad').toBeGreaterThanOrEqual(3);
  });

  describe('the generated page', () => {
    const svgs = Object.fromEntries(TYPES.map((t) => [t, svgOf(t)]));
    const titles = Object.fromEntries(TYPES.map((t) => [t, titleOf(t)]));
    const html = renderShowcase(manifest, { svgs, titles });

    it('is a self-contained HTML document — no external script/stylesheet/img requests', () => {
      expect(html.startsWith('<!doctype html>'), 'standalone document').toBe(true);
      expect(html, 'no external script').not.toMatch(/<script\b[^>]*\bsrc=/i);
      expect(html, 'no external stylesheet').not.toMatch(/<link\b[^>]*\brel=["']stylesheet/i);
      expect(html, 'diagrams are inline <svg>, never <img src>').not.toMatch(/<img\b/i);
    });

    it('inlines every diagram’s golden render and its REAL model title (drift-proof)', () => {
      for (const t of TYPES) {
        expect(html, `model title for ${t} (pulled from the model, not duplicated)`).toContain(
          esc(titles[t]),
        );
      }
      const svgCount = (html.match(/<svg\b/g) || []).length;
      expect(svgCount, 'one inline diagram per type').toBeGreaterThanOrEqual(TYPES.length);
    });

    it('embeds each type’s EXACT current golden SVG verbatim — the page can’t show a stale or re-rendered diagram', () => {
      // The builder inlines the committed `showcase-<type>.svg` after stripping only the XML
      // prolog/DOCTYPE (which the goldens don't carry), so the page must contain each golden BYTE FOR
      // BYTE. `index.test.ts` in turn pins every golden to the live renderer (expectGolden), so this
      // closes the chain page ← golden ← renderer: improve a renderer → its golden regenerates → the
      // showcase shows the new render, all enforced. A builder change that rescaled, re-rendered, or
      // dropped a diagram's SVG (while keeping its title) is caught here.
      const stripProlog = (svg: string): string =>
        svg.replace(/^\s*<\?xml[^>]*\?>\s*/i, '').replace(/^\s*<!DOCTYPE[^>]*>\s*/i, '');
      for (const t of TYPES) {
        expect(
          html.includes(stripProlog(svgs[t])),
          `showcase must embed the current golden SVG for ${t} verbatim (regenerate showcase-${t}.svg or rebuild the page)`,
        ).toBe(true);
      }
    });

    it('renders each diagram’s explanation, when-to-use, and on-paper guidance', () => {
      for (const d of manifest.diagrams) {
        expect(html, `whatItShows for ${d.type}`).toContain(esc(d.whatItShows));
        expect(html, `onPaper for ${d.type}`).toContain(esc(d.onPaper));
      }
    });

    it('each diagram deep-links into the editor (ADR-0048: ?example=showcase-<type>)', () => {
      for (const d of manifest.diagrams) {
        // the editor opens `?example=<key>` when the key names a shipped example; showcase-<type>
        // always exists (asserted above), so each link lands on that exact diagram, live.
        expect(html, `editor deep-link for ${d.type}`).toContain(`./?example=showcase-${d.type}`);
      }
    });

    it('renders the JTBD jobs, the family chooser questions, and the honesty notes', () => {
      for (const j of manifest.jobs) expect(html, `job: ${j.id}`).toContain(esc(j.label));
      for (const f of FAMILIES)
        expect(html, `chooser question: ${f.id}`).toContain(esc(f.question));
      for (const note of manifest.honesty) expect(html, 'honesty note').toContain(esc(note));
    });

    it('links back to the editor so the page is reachable both ways', () => {
      expect(html, 'a relative back-link to the editor root').toMatch(/href="\.\/"/);
    });

    it('offers print-to-paper and back-to-top affordances (UX, M25)', () => {
      expect(html, 'a Print / Save-as-PDF control for the on-paper use case').toMatch(
        /onclick="window\.print\(\)"/,
      );
      expect(html, 'a back-to-top link for the long page').toContain('href="#top"');
    });
  });
});
